const PDFDocument = require('pdfkit');
const { createObjectCsvWriter } = require('csv-writer');
const { promises: fs } = require('fs');
const path = require('path');

// Get __dirname in CommonJS
const __dirname = path.dirname(require.main?.filename || process.cwd());

/**
 * Generate PDF protocol sheet for session results
 */
const generateProtocolPDF = async (session, athletes, leaderboard) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text('OFFICIAL PROTOCOL SHEET', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(14).font('Helvetica').text(session.competition_name || 'Competition', { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(12).text(session.name, { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(10).text(`${session.gender === 'male' ? 'Men' : 'Women'} - ${session.weight_category}kg`, { align: 'center' });
      doc.moveDown(0.3);
      doc.text(new Date().toLocaleDateString(), { align: 'center' });
      
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1);

      // Results Table
      doc.fontSize(11).font('Helvetica-Bold');
      const tableTop = doc.y;
      const rowHeight = 25;
      
      // Table headers
      doc.text('Rank', 50, tableTop, { width: 40 });
      doc.text('Name', 100, tableTop, { width: 150 });
      doc.text('Country', 260, tableTop, { width: 60 });
      doc.text('Snatch', 330, tableTop, { width: 50 });
      doc.text('C&J', 390, tableTop, { width: 50 });
      doc.text('Total', 450, tableTop, { width: 50 });
      doc.text('Medal', 510, tableTop, { width: 35 });

      doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).stroke();

      // Table rows
      doc.font('Helvetica');
      let y = tableTop + 20;

      leaderboard.forEach((athlete, idx) => {
        if (y > 700) {
          doc.addPage();
          y = 50;
        }

        const rank = athlete.rank || idx + 1;
        doc.fontSize(10);
        doc.text(rank, 50, y, { width: 40 });
        doc.text(athlete.athlete_name, 100, y, { width: 150 });
        doc.text(athlete.country, 260, y, { width: 60 });
        doc.text(athlete.best_snatch || '-', 330, y, { width: 50 });
        doc.text(athlete.best_clean_and_jerk || '-', 390, y, { width: 50 });
        doc.text(athlete.total || '0', 450, y, { width: 50 });
        
        // Medal emoji
        if (athlete.medal === 'gold') doc.text('🥇', 510, y, { width: 35 });
        else if (athlete.medal === 'silver') doc.text('🥈', 510, y, { width: 35 });
        else if (athlete.medal === 'bronze') doc.text('🥉', 510, y, { width: 35 });

        y += rowHeight;
      });

      // Footer
      doc.fontSize(8).font('Helvetica').text(
        `Generated by WL System on ${new Date().toLocaleString()}`,
        50,
        750,
        { align: 'center' }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate CSV export for leaderboard
 */
const generateLeaderboardCSV = async (leaderboard, _sessionName) => {
  const tempDir = path.join(__dirname, '../../temp');
  
  // Ensure temp directory exists
  try {
    await fs.mkdir(tempDir, { recursive: true });
  } catch (err) {
    console.log('Temp dir exists or error:', err.message);
  }

  const timestamp = Date.now();
  const filename = `leaderboard_${timestamp}.csv`;
  const filepath = path.join(tempDir, filename);

  const csvWriter = createObjectCsvWriter({
    path: filepath,
    header: [
      { id: 'rank', title: 'Rank' },
      { id: 'athlete_name', title: 'Name' },
      { id: 'country', title: 'Country' },
      { id: 'weight_category', title: 'Weight Category' },
      { id: 'body_weight', title: 'Body Weight' },
      { id: 'best_snatch', title: 'Best Snatch' },
      { id: 'best_clean_and_jerk', title: 'Best Clean & Jerk' },
      { id: 'total', title: 'Total' },
      { id: 'medal', title: 'Medal' },
    ],
  });

  await csvWriter.writeRecords(leaderboard);
  
  return { filepath, filename };
};

/**
 * Generate CSV start list
 */
const generateStartListCSV = async (athletes, _sessionName) => {
  const tempDir = path.join(__dirname, '../../temp');
  
  try {
    await fs.mkdir(tempDir, { recursive: true });
  } catch (err) {
    console.log('Temp dir exists');
  }

  const timestamp = Date.now();
  const filename = `startlist_${timestamp}.csv`;
  const filepath = path.join(tempDir, filename);

  const csvWriter = createObjectCsvWriter({
    path: filepath,
    header: [
      { id: 'start_number', title: 'Start #' },
      { id: 'name', title: 'Name' },
      { id: 'country', title: 'Country' },
      { id: 'gender', title: 'Gender' },
      { id: 'weight_category', title: 'Weight Category' },
      { id: 'body_weight', title: 'Body Weight' },
      { id: 'team_name', title: 'Team' },
    ],
  });

  const records = athletes.map(a => ({
    start_number: a.start_number || '',
    name: a.name,
    country: a.country,
    gender: a.gender,
    weight_category: a.weight_category,
    body_weight: a.body_weight,
    team_name: a.team_name || '',
  }));

  await csvWriter.writeRecords(records);
  
  return { filepath, filename };
};

/**
 * Clean up temporary file
 */
const cleanupTempFile = async (filepath) => {
  try {
    await fs.unlink(filepath);
  } catch (err) {
    console.error('Failed to cleanup temp file:', err);
  }
};
